### ISSUE TITLE
Test Provider Available?

### ISSUE THREAD

**Issue by bjvetter** [Purebred/KeyShareConsumer#1]
Is there a KeyShare Provider that can be used for testing an integrated consumer against?

**Comment by Purebred** [comment]
SampleKeyProvider was pushed on Monday of this week along with a revised
version of the KeyShareConsumer that supports requesting filtered views of
keys from a provider.

From:  bjvetter notifications@github.com
Reply-To:  Purebred/KeyShareConsumer
<reply+011477a4c851828903a24440bb72ba1752ba5bc633fc3fca92cf0000000113701cde9
2a169ce097daabc@reply.github.com>
Date:  Wednesday, June 8, 2016 at 1:50 PM
To:  Purebred/KeyShareConsumer KeyShareConsumer@noreply.github.com
Subject:  [Purebred/KeyShareConsumer] Test Provider Available? (#1)
