### ISSUE TITLE
What is the purpose for the unzip functionality in importp12 method?

### ISSUE THREAD

**Issue by Rmpanga** [Purebred/KeyShareConsumer#2]
Summary
=======

I am trying to receive certificates from the KeyShareConsumer which should mimic the purebread registration application. 

In ViewController.mm and in the importp12 function, there is a block of code which I am confused by. 

Code
=====

```objective-c
OSStatus securityError = SecPKCS12Import(inPKCS12Data, (CFDictionaryRef)optionsDictionary, &items);

 if(0 == securityError)
{
 //Import cert to keychain (I understand this logic)
}
else
{
        //Get the destination folder for the files
        NSArray *paths = NSSearchPathForDirectoriesInDomains(NSDocumentDirectory, NSUserDomainMask, YES);
        NSString *documentsDirectory = [paths objectAtIndex:0];
        
        //Generate a file name using the sha1 hash of the certificate with .p8 extension for private key and .der for certificate
        NSString* zipFile = @"tmp.zip";
        NSString *zipPath = [documentsDirectory stringByAppendingPathComponent:zipFile];
       
        [pkcs12DataToImport writeToFile:zipPath atomically:YES];
        
        ZipFile *unzipFile= [[ZipFile alloc] initWithFileName:zipPath mode:ZipFileModeUnzip];
        if(NULL != unzipFile)
        {
            NSArray *infos= [unzipFile listFileInZipInfos];
            [unzipFile goToFirstFileInZip];
            
            for (FileInZipInfo *info in infos)
            {
                ZipReadStream *read1= [unzipFile readCurrentFileInZip];
                
                NSData *data= [read1 readDataOfLength:info.length];
               
                if(data)
                {
                    [self importP12:data password:password];
                }
                    
                [read1 finishedReading];
                [unzipFile goToNextFileInZip];
            }
            
            [unzipFile close];
            [[NSFileManager defaultManager] removeItemAtPath:zipPath error:nil];
        }
}

```
Questions
=======
Why is it assumed that the ***OSStatus securityError***  is thrown because of the p12 being zipped?

Shouldn't there be a check to see if the error is an  ***errSecUnknownFormat*** or an ***errSecDecode*** before that assumption is made?

Lastly, should I be expecting zipfiles from the Purebread registration app?

**Comment by carl-wallace** [comment]
You are likely right that there may be better error values to key off. You
will receive either a P12 or a zip file. The code here tries as P12 and
failing that tries as a zip before failing. The UTIs passed to the Purebred
app will dictate what you receive in return (as demonstrated in the Sample
Key Provider app). The list of UTIs is below. Those with zip in the name
return a zip file containing P12s and the others return single P12 files.

* com.rsa.pkcs-12
* purebred.select.all
* purebred.select.all_user
* purebred.select.device
* purebred.select.signature
* purebred.select.encryption
* purebred.select.authentication
* purebred.select.no_filter
* purebred.zip.all
* purebred.zip.all_user
* purebred.zip.device
* purebred.zip.signature
* purebred.zip.encryption
* purebred.zip.authentication
* purebred.zip.no_filter

From:  Richard Mpanga <notifications@github.com>
Reply-To:  Purebred/KeyShareConsumer
<reply+000f3de529df374e43cdaba0e46ff165e70fb3478b448b1092cf0000000118a377689
2a169ce19203ec0@reply.github.com>
Date:  Friday, March 15, 2019 at 10:23 AM
To:  Purebred/KeyShareConsumer <KeyShareConsumer@noreply.github.com>
Cc:  Subscribed <subscribed@noreply.github.com>
Subject:  [Purebred/KeyShareConsumer] What is the purpose for the unzip
functionality in importp12 method? (#2)

**Comment by Rmpanga** [comment]
Awesome, this make sense. I have another question but ill close this issue and create a new one. Thanks!
