### ISSUE TITLE
Why is the p12 certificate and the password written on disk?

### ISSUE THREAD

**Issue by Rmpanga** [Purebred/KeyShareConsumer#3]
Summary
======

I am trying to wrap my head around the need to save the p12File and the password to a file. Since the password will be stored in plaintext that seems to be very insecure. 

Code
====
```Objective-c
//Called to parse a PKCS12 object, decrypt it and import it into app's key chain
- (void)importP12:(NSData*) pkcs12DataToImport password:(NSString*)password
{
    //Get the destination folder for the files
    NSArray *paths = NSSearchPathForDirectoriesInDomains(NSDocumentDirectory, NSUserDomainMask, YES);
    NSString *documentsDirectory = [paths objectAtIndex:0];
    
    //Generate a file name using the sha1 hash of the certificate with .p8 extension for private key and .der for certificate
    NSString* p12File = @"p12ForReview.p12";
    NSString* passFile = @"p12Password.txt";
    NSString *p8Path = [documentsDirectory stringByAppendingPathComponent:p12File];
    NSString *passPath = [documentsDirectory stringByAppendingPathComponent:passFile];
    
    //Write the private key and certificate to a pair of files
    [pkcs12DataToImport writeToFile:p8Path atomically:YES];
    [password writeToFile:passPath atomically:YES];  // < -- Insecure?

```

Question
===
Since the p12 file and the password are already in memory, why should the developer save these files on disk?

**Comment by carl-wallace** [comment]
You don't need to save it. An unstated part of the purpose of the Key Share
Consumer app is to strongly demonstrate that once the key is passed across
the document provider boundary it is the responsibility of the receiving app
to care for it (and, in turn, the responsibility of device owners/key owners
to choose those apps carefully). I don't expect any app to follow Key Share
Consumer's lead and save plaintext P8 files to the iTunes File Share:-)  I
would expect an app to retain the P12 and password just long enough to
import it into the app's slice of the system key chain or into its own key
chain.

From:  Richard Mpanga <notifications@github.com>
Reply-To:  Purebred/KeyShareConsumer
<reply+000f3de529eece145363a40a83376fad1b611af38cdb37a792cf0000000118a386089
2a169ce1920b677@reply.github.com>
Date:  Friday, March 15, 2019 at 11:26 AM
To:  Purebred/KeyShareConsumer <KeyShareConsumer@noreply.github.com>
Cc:  Subscribed <subscribed@noreply.github.com>
Subject:  [Purebred/KeyShareConsumer] Why is the p12 certificate and the
password written on disk? (#3)

**Comment by Rmpanga** [comment]
Perfect. Thanks again!
