### ISSUE TITLE
What file types to the Purebread UTIs correspond to? 

### ISSUE THREAD

**Issue by Rmpanga** [Purebred/KeyShareConsumer#4]
I understand that  com.rsa.pkcs-12 corresponds to a p12 file type. 

I am confused as to what file types the purebread specific UTI correspond to. 

* purebred.select.all
* purebred.select.all_user
* purebred.select.device
* purebred.select.signature
* purebred.select.encryption
* purebred.select.authentication
* purebred.select.no_filter

Are these also p12 files? Are they filters that the purebread uses to display the certificates ?
Also I had a question about this statement  in the readme 

> "By default, the Purebred Registration app serves up the most recent keys for the indicated types."

Does this mean that older keys of the indicated type will not be displayed by the purebread? 

The reason I am asking is that one customer of ours is only seeing 1 out of 4 certificates on purebread shareextension. I used the UTIs above in the document picker including the com.rsa.pkcs-12.

**Comment by carl-wallace** [comment]
Inline…

**Comment by Rmpanga** [comment]
Thanks again for the quick response.
